version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Chrome Headless...
      - apt-get update
      - apt-get install -yq google-chrome-stable
      - npm install -g @angular/cli
      - npm install

  pre_build:
    commands:
      - echo Running unit tests...
      - CHROME_BIN=/usr/bin/google-chrome-stable
      - ng test

  build:
    commands:
      - echo Build started
      - ng build

artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
  discard-paths: yes
