version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source code dependencies...
      - npm install -g @angular/cli
      - npm install

  pre_build:
    commands:
      - echo Running unit tests...
      - ng test --watch=false --browsers=ChromeHeadless

  build:
    commands:
      - echo Build started
      - ng build

artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
  discard-paths: yes
